version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
      args:
        - DEV=true
    image: myapp:dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - dev-static-data:/vol/web
    command: sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
      args:
        - DEV=true
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  dev-static-data:


# run docker-compose run --rm app python manage.py makemigrations