name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -r requirements/production.txt
      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=config.django.local" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV

          echo "DB_NAME=${{ DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ DB_PORT }}" >> $GITHUB_ENV
          echo "DB_SSLMODE=${{ DB_SSLMODE }}" >> $GITHUB_ENV

          echo "CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}" >> $GITHUB_ENV
          echo "CACHE_URL=${{ secrets.CACHE_URL }}" >> $GITHUB_ENV

          echo "EMAIL_BACKEND=${{ secrets.EMAIL_BACKEND }}" >> $GITHUB_ENV
          echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> $GITHUB_ENV
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> $GITHUB_ENV
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> $GITHUB_ENV
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> $GITHUB_ENV
          echo "EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}" >> $GITHUB_ENV
          echo "DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }}" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          python manage.py test

    #   - name: Build & push Docker image
    #     uses: mr-smithers-excellent/docker-build-push@v6
    #     with:
    #       image: ennyboy/cosplitzbackend
    #       registry: docker.io
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
